import os

class Config(object):
    SECRET_KEY=os.environ['SECRET_KEY']
    CACHE_TYPE = "SimpleCache"
    CACHE_DEFAULT_TIMEOUT = 300

class ProductionConfig(Config):
    FLASK_DEBUG = False
    TESTING = False
    #DATABASE
    DATABASE_USER = os.environ['DATABASE_USER']
    DATABASE_PASSWORD = os.environ['DATABASE_PASSWORD']
    DATABASE_NAME = os.environ['DATABASE_NAME']
    DATABASE_ADDRESS = os.environ['DATABASE_ADDRESS']
    DATABASE_PORT = os.environ['DATABASE_PORT']
    SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_ADDRESS}:{DATABASE_PORT}/{DATABASE_NAME}"
    SQLALCHEMY_TRACK_MODIFICATIONS=False

class DevelopmentConfig(Config):
    FLASK_DEBUG = True
    TESTING = True
    #DATABASE
    DATABASE_PASSWORD = os.environ['DATABASE_PASSWORD']
    DATABASE_USER = os.environ['DATABASE_USER']
    DATABASE_NAME = os.environ['DATABASE_NAME']
    DATABASE_ADDRESS = os.environ['DATABASE_ADDRESS']
    DATABASE_PORT = os.environ['DATABASE_PORT']
    SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_ADDRESS}:{DATABASE_PORT}/{DATABASE_NAME}"
    SQLALCHEMY_TRACK_MODIFICATIONS=False